### PR TITLE
Database set for the current functionality

### PR DESCRIPTION
**Pull request by StefanBosev**
Required columns of information for the registration now coincide with the columns in the database. Closing issue "Database" for now.

### CODE REVIEW

**Comment by stephie306** [comment]
With this request you want to merge into main branch. Иs there a reason or is it without wanting to? Оtherwise it's okay.

**Comment by StefanBosev** [comment]
It was a mistake. I didn't change the default branch for merge. I'll fix it right up

**Comment by StefanBosev** [comment]
Is it ok now?

**Comment by stephie306** [comment]
Everything is ok now.

**Comment by stephie306** [comment]
Little missclick.

**Pull request merged**
